### PR TITLE
Added GUI frontend

### PR DESCRIPTION
**Pull request by Aayush-hub**
Fixes: #159 
Added a GUI frontend to correct scratched images which make program user-friendly. 

How to Run Program:
1. Install PySimpleGUI   `pip install PySimpleGUI`
2. Run `GUI.py` file.
3. Click browse and select your image from test_images/old_w_scratch folder to remove scratches.
4. Click Modify Photo button.
5. Wait for a while and see results on GUI window.
6. Exit window by clicking Exit Window.

### CODE REVIEW

**Comment by zhangmozhe** [comment]
Cool! Thanks for your contribution on this! Could you please explain the usage by editing the readme file as well?

**Comment by Aayush-hub** [comment]
@zhangmozhe Done Sir!

**Comment by Aayush-hub** [comment]
> Cool! Thanks for your contribution on this! Could you please explain the usage by editing the readme file as well?

@zhangmozhe Done Sir!

**Comment by SeaCelo** [comment]
Please check line 199 of the guy.py file. I think there is a hard coded path there.

**Comment by Aayush-hub** [comment]
> Please check line 199 of the gui.py file. I think there is a hard coded path there.

@SeeCelo Great Catch, thanks for letting me know!

**Comment by zhangmozhe** [comment]
Hi @Aayush-hub,  we've recently released the code which supports high-resolution images. Could you please have a check whether the GUI support this release?

**Comment by Aayush-hub** [comment]
> Hi @Aayush-hub, we've recently released the code which supports high-resolution images. Could you please have a check whether the GUI support this release?

@zhangmozhe Sure, checking. Will let you know.

**Comment by Aayush-hub** [comment]
> Hi @Aayush-hub, we've recently released the code which supports high-resolution images. Could you please have a check whether the GUI support this release?

@zhangmozhe Yes its working fine with GUI, we just need to add HR flag by default in its code (which will have no extra effect on normal images), or we can create a different button which can be used for high resolution image. Do let me know needs to be done??

**Pull request merged**
