### PR TITLE
[Feature] Added image filter script

### PR DESCRIPTION
**Pull request by Aayush-hub**
Fixes: #125 
Added script to apply filters on output image. Currently added script to make output image black and white.
Will adding more scripts to more beautify images according to choice. This a feature which can help edit old images to look cool in this time.

# Sample Video:

https://user-images.githubusercontent.com/65889104/112759421-875fa180-9010-11eb-87bd-66cd79222127.mp4

### CODE REVIEW

**Comment by zhangmozhe** [comment]
Good idea and thanks for your contribution~ Could you please add more image filters and then we will merge into the project.

**Comment by Aayush-hub** [comment]
@zhangmozhe Done with adding some more filters like edge_enhance , detailing , smoothing, sharpen . Could you please suggest more filters if needed or should I use OpenCV to add more filters or not?

**Comment by zhangmozhe** [comment]
@Aayush-hub Thanks for your work. Can you add the aesthetical photo filters like the ones in photoshops or Lightroom? I think users may be interested in beautifying the photos, and I am not sure adding grains or making photos to black and white again is attractive for them.

**Comment by Aayush-hub** [comment]
> @Aayush-hub Thanks for your work. Can you add the aesthetical photo filters like the ones in photoshops or Lightroom? I think users may be interested in beautifying the photos, and I am not sure adding grains or making photos to black and white again is attractive for them.

Yes this was exactly I was thinking about, but I have used Pillow module before, so I added filters according to it, and I asked you that can I use OpenCv. But now I got clearance,  so I will come up with new changes soon.

**Comment by Aayush-hub** [comment]
@zhangmozhe Done with changes. Added some cool filters. Can you please have a look at it and review it.

## Bright

https://user-images.githubusercontent.com/65889104/113422532-805ad980-93ea-11eb-9397-ec68047356e9.mp4

## Cartoon 

https://user-images.githubusercontent.com/65889104/113422563-8d77c880-93ea-11eb-8491-0237b2d17f09.mp4

## Contrast


https://user-images.githubusercontent.com/65889104/113422599-9c5e7b00-93ea-11eb-9d0c-bb23f1d6ee60.mp4

## Daylight

https://user-images.githubusercontent.com/65889104/113422637-aed8b480-93ea-11eb-9dc8-9cee396326c0.mp4

## Detail

https://user-images.githubusercontent.com/65889104/113422657-b730ef80-93ea-11eb-84ca-4f1ef60dc4a8.mp4

## Invert

https://user-images.githubusercontent.com/65889104/113422671-be57fd80-93ea-11eb-9d2d-10d758a5ab46.mp4

## Kernel Sharpening

https://user-images.githubusercontent.com/65889104/113422702-c9ab2900-93ea-11eb-9a4a-699622e67028.mp4

## Sketch

https://user-images.githubusercontent.com/65889104/113422733-d62f8180-93ea-11eb-8ebe-fa3edc4b4546.mp4

## Summer

https://user-images.githubusercontent.com/65889104/113422758-df205300-93ea-11eb-9c35-a82e8df185d1.mp4

## Winter

https://user-images.githubusercontent.com/65889104/113422786-e8a9bb00-93ea-11eb-8e7a-51031a56791b.mp4

## Vintage

https://user-images.githubusercontent.com/65889104/113422796-f0695f80-93ea-11eb-892f-86dc49b6641e.mp4

## 60's Tv

https://user-images.githubusercontent.com/65889104/113422826-f9f2c780-93ea-11eb-81c6-79ca3a456226.mp4

**Comment by Aayush-hub** [comment]
@zhangmozhe Ping!! Please review my PR.

**Comment by zhangmozhe** [comment]
Hi @Aayush-hub, thanks for your contribution. We checked the color filter effect you created, but our team believes that the project is for image restoration that cannot be accomplished by other software, yet the color filter effect can be added with other commercial tools. So we are sorry that we decide not to merge this function.

Would you mind to create an issue so as to benefit other users who need this function? 

Still, we sincerely thank your valuable time and nice contribution.

**Comment by Aayush-hub** [comment]
> Hi @Aayush-hub, thanks for your contribution. We checked the color filter effect you created, but our team believes that the project is for image restoration that cannot be accomplished by other software, yet the color filter effect can be added with other commercial tools. So we are sorry that we decide not to merge this function.
> 
> Would you mind to create an issue so as to benefit other users who need this function?
> 
> Still, we sincerely thank your valuable time and nice contribution.

@zhangmozhe Right, we can add filters using other commercial tools, but I thought it will be great if users can try using some filters within the project and can import a final image from here. But its fine, thank you for your valuable time.

For the issue we can reopen the previous one for which this PR was, for the users who need this function.

**Comment by Aayush-hub** [comment]
@zhangmozhe Secondly, you can ping me if the project needs a script which can remove noise from the images, which enhances the image quality and make them clear, so that I can create a issue and start working on it after the idea being approved by you.

**Comment by zhangmozhe** [comment]
@Aayush-hub Thanks again! We will definitely let you know if new feature is needed.

**Pull request closed without merging**
