### PR TITLE
Code formatting with black

### PR DESCRIPTION
**Pull request by abdullahselek**
With this PR codes formatted using [https://github.com/psf/black](https://github.com/psf/black) which improves the coding standards and enables easy readibility.

### CODE REVIEW

**Review by sallieover — APPROVED** [review]

**Review by imsubhamsingh — APPROVED** [review]

**Comment by imsubhamsingh** [comment]
@abdullahselek instead of formatting the code files individually its better to add black module in a pre-commit hook. That would be good practice here.

**Comment by phadytou** [comment]
Thank you so much

**Review by phadytou — APPROVED** [review]
Thank you so much

**Review by phadytou — APPROVED** [review]

**Comment by phadytou** [comment]
> Thank you so much

**Review by phadytou — APPROVED** [review]

**Comment by phadytou** [comment]
> Thank you so much

**Pull request closed without merging**
